/**
 * 
 */
package artemisLite;

/**
 * @author stu_m
 *
 */
public enum ElementName {
LAUNCH_PAD_39B, VEHICLE_ASSEMBLY_BUILDING, YOUNG_CRIPPEN_FIRING_ROOM, RS_25_ENGINES, BOOSTERS, 
SERVICE_MODULE, CREW_MODULE, LAUNCH_ABORT_SYSTEM, LUNAR_LANDERS, ARTEMIS_GENERATION_SPACESUITS; 
}
